version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      text: ${TAG}
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
